### ISSUE TITLE
Building with Xcode 6

### ISSUE THREAD

**Issue by weefuzzy** [flucoma/flucoma-core#8]
See issue #5 : it seems things won't compile in XCode 6 on 10.9. The first error doesn't make a great deal of sense: 
```bash 
/Users/vowel/Desktop/flucoma-sc/build/_deps/flucoma-core-src/include/clients/rt/../common/ParameterTypes.hpp:173:17: error: 
      no viable conversion from 'const std::array<std::pair<FloatUnderlyingType,
      FloatUnderlyingType>, 2>' to 'value_type' (aka 'std::__1::pair<double,
      double>')
        : value{x}
```
but is possibly due to clang 3.5 being more fussy about brace initialization than required. 

Unfortunately, it's not possible to run XCode 6 post-Yosemite, which makes testing this harder.

**Comment by weefuzzy** [comment]
Note to self, now able to reproduce on Mojave using binaries of clang 3.5 and the 10.9 SDK from https://github.com/phracker/MacOSX-SDKs (we need both for ABI compatibility). 

Incantation: 
```bash
export CPPFLAGS="-I/<clang_path>/include -I/<clang_path>/include/c++/v1"
export LDFLAGS="-L/<clang_path>/lib -Wl,-rpath,/<clang_path>/lib"
cmake -C<my CMake vars> -DCMAKE_CXX_COMPILER="/<clang_path>/bin/clang++" -DCMAKE_OSX_SYSROOT=<sdk path> ..
```

**Comment by weefuzzy** [comment]
Turns out we are running afoul of this clang 3.5 bug https://bugs.llvm.org/show_bug.cgi?id=14858
(especially, in terms of symptoms this duplicate https://bugs.llvm.org/show_bug.cgi?id=22328). This may not be all, of course. 

The upshot is that a C++ STL function `std::index_sequence_for<Ts>` doesn't work reliably under this version of clang. A workaround is to replace all instances with `std::make_index_sequence<sizeof...(Ts)>`. 

I will need to mull on whether I'm prepared to do that for a bug in such an old compiler. I guess, worst case, we could make a patch.

**Comment by vowelmusic** [comment]
Thanks for working all this out, trust me to find a bug...
I'll keep an eye on here in case of a fix.
All the best.

**Comment by weefuzzy** [comment]
Hi @vowelmusic, 

I managed to get it to build here in the end, and I think the changes will be minor enough that we'll be able to commit them. If you're able to move up to XCode 6.4 (which uses clang 3.6), I'd reccomend that, because it seems like 3.5 had quite a few strange things in it. I'll ping you when the changes are pushed, and we can have another go at getting you up and running.

**Comment by vowelmusic** [comment]
Cheers!
I don't know if xcode6.4 will work on 10.9.5 - I'll have another look.
Thanks again.
Ps. If everything installs correctly is it just the .scx files that are needed for the plugins folder & are these system specific?
ATB.

**Comment by weefuzzy** [comment]
@vowelmusic I've done the updates now, so it should be ready for you to try again. 

If you're only building for your particular machine, I suggest that you add the following when you run CMake: `-DFLUID_ARCH=-march=native` . This will tell the compiler to optimize specific to the capabilities of your CPU, rather than rely on our defaults that may not work for you here. 

> I don't know if xcode6.4 will work on 10.9.5 - I'll have another look

This *should* work with 6.2, I just think that 6.4 is going to be more reliable for you long term.

> If everything installs correctly is it just the .scx files that are needed for the plugins folder & are these system specific?

After running `make install`, you should have a folder structure like 
```
flucoma-sc
|
|– installl
   |
   |– FluidCorpusManipulation 
```

You'll want to copy the whole FluidCorpusManipulation folder to your supercollider extensions folder as it has the .scx files (yes, platform specific) but also .sc and .schelp files.

**Comment by vowelmusic** [comment]
Thanks for explaining - I understand much better now.
Unfortunatley I still get an error, but it is much smaller:

[TerminalError.zip](https://github.com/flucoma/flucoma-core/files/4797990/TerminalError.zip)

**Comment by weefuzzy** [comment]
Arg! Can't recreate this one here against plain clang (as opossed to Apple clang) and, worryingly, looks like a more fundamental C++14 feature that isn't working. 

Would you be able to give Xcode 6.4 a spin?

**Comment by vowelmusic** [comment]
Sure, will it be easy to revert to 6.2 if unsuccessful?
Also - while looking on a clang forum,
someone mentioned sending a message from Terminal to clang 
to make it C++14 compliant.
Could this be a possibility? (don't have the link I'm afraid)

**Comment by weefuzzy** [comment]
You should be able to have both installed at the same time if you name one differently.

**Comment by vowelmusic** [comment]
!!!!!!! brilliant!

I renamed Xcode6.2 installed Xcode6.4 & restarted everything.
The new Xcode icon has the noEntry(notWorking) sign,
but it must have solved the problem with clang.
Am I ok to leave my system like this as I use SublimeText for most things anyway?

I was kind of desperate for these so thank you.
Everyone at FluCoMa has been really helpful,
above & beyond.
I look forward to following the project :)
ATB.

**Comment by weefuzzy** [comment]
Great! Thanks for reporting and for sticking with it: it's really useful for us. Have fun. 

The Xocde thing sounds un-ideal, but if it's working, you should be ok. You can switch between the version of the compiler used on the command line using `xcode-select`, or from the preferences of the working version. Alterntiavely, you should be fine to get rid of it if you like.
