### ISSUE TITLE
Doesn't compile with macOS 10.12 SDK

### ISSUE THREAD

**Issue by olilarkin** [flucoma/flucoma-core#69]
If you try and compile flucoma-core against the 10.12 SDK that is installed with Xcode 13, there is a conflict with some blas headers. I'm not sure why but it tries to include MKL support which has some conflicting types with the Accelerate blas headers.

```
In file included from /Users/oli/Dev/flucoma-core/examples/describe.cpp:19:
In file included from /Users/oli/Dev/flucoma-core/include/algorithms/public/Loudness.hpp:16:
In file included from /Users/oli/Dev/flucoma-core/include/algorithms/public/../util/TruePeak.hpp:13:
In file included from /Users/oli/Dev/flucoma-core/include/algorithms/public/../util/FFT.hpp:15:
In file included from /Users/oli/Dev/flucoma-core/build/_deps/hisstools-src/HISSTools_FFT/HISSTools_FFT.h:40:
In file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework/Headers/Accelerate.h:20:
In file included from /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework/Headers/../Frameworks/vecLib.framework/Headers/vecLib.h:50:
/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/fortran_blas.h:27:5: error: conflicting types for 'icamax_'
int icamax_(int *n, void *cx, int *incx)
    ^
In file included from /Users/oli/Dev/flucoma-core/examples/describe.cpp:17:
In file included from /Users/oli/Dev/flucoma-core/build/_deps/eigen-src/Eigen/Core:100:
In file included from /Users/oli/Dev/flucoma-core/build/_deps/eigen-src/Eigen/src/Core/util/MKL_support.h:113:
/Users/oli/Dev/flucoma-core/build/_deps/eigen-src/Eigen/src/Core/util/../../misc/blas.h:67:8: note: previous declaration is here
int    BLASFUNC(icamax)(int *, float  *, int *);
       ^
```

**Comment by olilarkin** [comment]
Note: it works with macOS 11 SDK

**Comment by weefuzzy** [comment]
This should already be fixed on the dev branch. If you comment out the
EIGEN_USE_BLAS bit in CMakeLists for flucoma-core you should be golden

**Comment by olilarkin** [comment]
great, thanks!
